name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stefan-hoeck/idris2-pack:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pack
        uses: actions/cache@v4
        with:
          path: /root/.pack
          key: ${{ runner.os }}-pack-${{ hashFiles('**/*.ipkg', 'pack.toml') }}
          restore-keys: |
            ${{ runner.os }}-pack-

      - name: Build and Install Z3
        run: |
          cd
          apt-get update
          apt-get install -y build-essential python3 git wget unzip

          wget https://github.com/Z3Prover/z3/releases/download/z3-4.16.0/z3-4.16.0-x64-glibc-2.39.zip
          unzip z3-4.16.0-x64-glibc-2.39.zip
          rm -f z3-4.16.0-x64-glibc-2.39.zip
          cp -R z3-4.16.0-x64-glibc-2.39/bin/* /root/.local/bin/

      - name: System info
        run: |
          idris2 --version
          pack info
          z3 --version

      - name: Build library
        run: pack build smtlib

      - name: Run tests
        run: pack test smtlib
